### ISSUE TITLE
ArrayIndexOutOfBoundsException during application 

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gateplugin-LearningFramework#112]
With the pytorch backend, we get the following error when applying a model to chunking:

```
Controller ended with error 1
java.lang.ArrayIndexOutOfBoundsException: 1
    at gate.plugin.learningframework.ModelApplication.addSurroundingAnnotations(ModelApplication.java:298)
    at gate.plugin.learningframework.LF_ApplyChunking.process(LF_ApplyChunking.java:156)
    at gate.plugin.learningframework.AbstractDocumentProcessor.execute(AbstractDocumentProcessor.java:259)
    at gate.util.Benchmark.executeWithBenchmarking(Benchmark.java:291)
    at gate.creole.ConditionalSerialController.runComponent(ConditionalSerialController.java:172)
    at gate.creole.SerialController.executeImpl(SerialController.java:157)
    at gate.creole.ConditionalSerialAnalyserController.executeImpl(ConditionalSerialAnalyserController.java:225)
    at gate.creole.ConditionalSerialAnalyserController.execute(ConditionalSerialAnalyserController.java:132)
    at gate.util.Benchmark.executeWithBenchmarking(Benchmark.java:291)
    at gate.gui.SerialControllerEditor$RunAction$1.run(SerialControllerEditor.java:1759)
    at java.lang.Thread.run(Thread.java:748)
```

**Comment by johann-petrak** [comment]
What seems to happen is that the target we get back is just an empty string.
This in turns seems to be caused by the fact that some targets in the training set are just an empty string. So the real bug is that such targets get created for some reason.
