### ISSUE TITLE
Exception when training regression problems

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gateplugin-LearningFramework#23]
The following exception occurs when training GaussianProcesses or SMO on the abalone regression problem:

````
Using target feature name from model: review
gate.util.GateRuntimeException: Error during training of Weka
algorithm class weka.classifiers.functions.GaussianProcesses
    at gate.plugin.learningframework.engines.EngineWeka.trainModel(EngineWeka.java:151)
    at gate.plugin.learningframework.LF_TrainRegression.afterLastDocument(LF_TrainRegression.java:172)
    at gate.plugin.learningframework.AbstractDocumentProcessor.controllerExecutionFinished(AbstractDocumentProcessor.java:91)
    at gate.creole.ConditionalSerialAnalyserController.invokeControllerExecutionFinished(ConditionalSerialAnalyserController.java:554)
    at gate.creole.ConditionalSerialAnalyserController.execute(ConditionalSerialAnalyserController.java:142)
    at gate.util.Benchmark.executeWithBenchmarking(Benchmark.java:291)
    at gate.gui.SerialControllerEditor$RunAction$1.run(SerialControllerEditor.java:1734)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 54
    at weka.core.SparseInstance.toDoubleArray(SparseInstance.java:425)
    at weka.filters.unsupervised.attribute.Normalize.batchFinished(Normalize.java:304)
    at weka.filters.Filter.useFilter(Filter.java:676)
    at weka.classifiers.functions.GaussianProcesses.buildClassifier(GaussianProcesses.java:334)
    at gate.plugin.learningframework.engines.EngineWeka.trainModel(EngineWeka.java:147)
    ... 7 more
````

**Comment by johann-petrak** [comment]
Fixed by 98d7815127ff1237235679014912d5c227689258
