### ISSUE TITLE
Implement our own options parsing class and use in Parms

### ISSUE THREAD

**Issue by johann-petrak** [GateNLP/gateplugin-LearningFramework#41]
Currently we use a modified version of apache commons-cli: originally it looked like the best match, then we had to hack it and now it turns out this was a very bad idea: GCP also uses commons-cli which gets loaded first so our code throws an exception:

```
java.lang.IllegalAccessError: tried to access method
org.apache.commons.cli.Options.getOptionGroups()Ljava/util/Collection;
from class org.apache.commons.cli.DefaultParser
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:113)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:80)
        at org.apache.commons.cli.DefaultParser.parse(DefaultParser.java:64)
        at gate.plugin.learningframework.engines.Parms.<init>(Parms.java:93)
        at gate.plugin.learningframework.engines.EngineLibSVM.trainModel(EngineLibSVM.java:157)
        at gate.plugin.learningframework.LF_TrainClassification.afterLastDocument(LF_TrainClassification.java:201)
        at gate.plugin.learningframework.AbstractDocumentProcessor.controllerExecutionFinished(AbstractDocumentProcessor.java:100)
        at gate.creole.ConditionalSerialAnalyserController.invokeControllerExecutionFinished(ConditionalSerialAnalyserController.java:554)
        at gate.cloud.batch.PooledDocumentProcessor.dispose(PooledDocumentProcessor.java:367)
        at gate.cloud.batch.BatchRunner$JobMonitor.run(BatchRunner.java:364)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by ianroberts** [comment]
Or move your hacked version into a different package.

**Comment by greenwoodma** [comment]
my question would be why do you need to hack it? surely there must be a way of using it "as is"

**Comment by johann-petrak** [comment]
Yes, changing the package name is probably a good idea until
a proper fix is found. The change is small anyway, currently I just
include the diff in the LF distribution

https://github.com/GateNLP/gateplugin-LearningFramework/blob/master/commons-cli.diff

Mark, I cannot really remember all the details very much but as far as I
remember,
I needed something to work differently in an urgency and hacking the
right version was the fastest way to do this - I had always been planning
on replacing it anyway (for other reasons as well) so I did not bother
to make an attempt to do it right. As it turns out, I never really got
around
replacing it.

What I need in the LF is an options parser that will only handle those
options
which it knows about, removing them from the parsed command line or from
the parameters object so the unhandled ones can be passed on to the
next module that may need parameters. This is how I try to handle
parametrization of various aspects of training/application/exporting in the
LF
without having to have a separate parameters parameter for every component
that may need to get parametrized and without the main PR having to know
about everyone else's parameters.
There is even an issue for this but my impression is that commons-cli did
not receive much love recently:
  https://issues.apache.org/jira/browse/CLI-257

I am really dissatisfied with practically all option parsing libraries I
know, so
at some point I will probably just write my own unless I finally find one I
like.

j.

**Comment by johann-petrak** [comment]
Accidently added wrong commit message
