### ISSUE TITLE
NPE when exporting 

### ISSUE THREAD

**Issue by tasoslytos** [GateNLP/gateplugin-LearningFramework#70]
When I tried to export, I had the error message: 

java.lang.NullPointerException
	at gate.plugin.learningframework.engines.Info.save(Info.java:122)
	at gate.plugin.learningframework.export.CorpusExporterMR.exportMeta(CorpusExporterMR.java:76)
	at gate.plugin.learningframework.export.CorpusExporterMRARFF.export(CorpusExporterMRARFF.java:62)
	at gate.plugin.learningframework.LF_Export.afterLastDocument(LF_Export.java:330)
	at gate.plugin.learningframework.AbstractDocumentProcessor.controllerExecutionFinished(AbstractDocumentProcessor.java:93)
	at gate.creole.ConditionalSerialAnalyserController.invokeControllerExecutionFinished(ConditionalSerialAnalyserController.java:554)
	at gate.creole.ConditionalSerialAnalyserController.execute(ConditionalSerialAnalyserController.java:142)
	at gate.util.Benchmark.executeWithBenchmarking(Benchmark.java:291)
	at gate.gui.SerialControllerEditor$RunAction$1.run(SerialControllerEditor.java:1759)
	at java.lang.Thread.run(Thread.java:745)

**Comment by johann-petrak** [comment]
Could you please add the following info: your operating system, the java version and, if possible, details about the dataset and parameters used when exporting?

**Comment by tasoslytos** [comment]
Today I tried to generate the error, I couldn't. However, my details:

windows 10
Java version 8, update 171

LF_Export parameters: 
classAnnotationType : Person
exporter: EXPORTER_ARFF_CLASS
instanceType: Token
scale_Features: None
targetType: NOMINAL

Dataset: Train dataset from Wednesday 13 June, Module 3, Session 4 from:
https://gate.ac.uk/wiki/TrainingCourseJune2018/index.html

**Comment by johann-petrak** [comment]
Unable to reproduce
